### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by eyedean** [sideway/joi-date#26]
@hapi/joi has a .d.ts type definition for Typescript at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi__joi/index.d.ts

I was wondering if there is a .d.ts support for joi-date as well.  I have a relatively big project built in Typescript and heavily using Joi, so without a .d.ts file, I cannot use joi-date.

(Sorry that I am removing the template for creating issues.  I don't think node version or other information apply to this.)

Thanks.

**Comment by LorhanSohaky** [comment]
Any news?

**Comment by hueniverse** [comment]
The template contains other information including under which support plan this is opened. Next time please just fill in the template as asked.

There is no official TS support for joi as of yet including this module and I don't have any idea when it will be available.

**Comment by pleytonsoftware** [comment]
Hi. Just for everyone that comes to here to know about the support in Typescript.

If there is any official support or not, I am not sure but I am leaving this over here for you.
```typescript
declare module '@hapi/joi-date' {
    import { Extension } from '@hapi/joi';
    const JoiDate: Extension;
    export default JoiDate;
}
```

I hope it helps. :)

**Comment by jweyrich** [comment]
The following should suffice to make the compiler happy about `.format()`:

```
declare module "Joi" {
  interface DateSchema {
    format(format: string): this;
  }
}
```

@hueniverse Any chances to get this definition into the repo?

**Comment by ThiagoFelippi** [comment]
Alternatively you can add just:
```
import * as Extension from "@joi/date";
import * as joi from "joi";

const joiDate = joi.extend(Extension);
```

This will not add types but will run code correctly

**Comment by hueniverse** [comment]
If someone submits a PR that copies the definitions from DT here and makes sure they are up to date, I'll review. Need to add a test file with the lab -Y flag similar to how other sideway modules are set up. Type tests must include at least one expected error.

**Comment by kanongil** [comment]
@hueniverse There does not appear to be any existing definitions in DT.
