### ISSUE TITLE
Question: Which Version of @hapi/joi Does v2 of joi-date Support?

### ISSUE THREAD

**Issue by CatGuardian** [sideway/joi-date#29]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.13.1
* *module version*: joi-date version 2.0.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

I have some questions:

1. What version of joi does joi-date 2.0.1 support?

2. What version of joi-date is supported by joi 15?

3. According to the hapi documentation, it looks like joi v15.1.1 is currently under support (https://hapi.dev/resources/status/#joi) and that joi-date v2.0.1 is the only one currently under support (https://hapi.dev/module/joi-date#usage). So my assumption is that joi-date v2.0.1 should work with joi v15.1.1 but when I install joi v15.1.1 and joi-date v2.0.1, I get a runtime error. The question here is that since joi v15.1.1 is supported, shouldn't there be a version of joi-date that is supported and that version listed in the joi-date documentation that I linked? See below for runtime error:

```
{
... // other stuff omitted
"name" [1]: -- missing --
}

[1] "name" is required

... // stack trace omitted
```

4. Should we document the answers to the questions above to help other developers understand which version of joi-date to be using and to avoid them having similar confusion?

Thank you for helping me understand whats going on! Much appreciated.

:)

**Comment by hueniverse** [comment]
joi-date v2 requires joi v16 or newer. joi-date v1 works with older versions.

Note that the only currently supported versions are joi-date v2 and joi v17. All previous versions are deprecated and no longer maintained. There is a commercially licensed version available for legacy versions.

**Comment by CatGuardian** [comment]
Don't we think there should be some documentation explaining this somewhere?
