### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by doktormerlin** [sideway/joi-date#34]
#### Context

* *node version*: All
* *module version*: All

#### What are you trying to achieve or the steps to reproduce ?

The documentation on the hapi site is missing. If you click on the documentation link, it leads to a 404. See for yourself: https://hapi.dev/family/joi-date/

**Comment by Nargonath** [comment]
Joi is not part of the hapi ecosystem anymore. You'll find the `joi-date` documentation here: https://joi.dev/module/joi-date/.
