### ISSUE TITLE
Could not find a declaration file for module '@hapi/joi-date'

### ISSUE THREAD

**Issue by fnoquiq** [sideway/joi-date#36]
* *is this issue currently blocking your project?* nop
* *is this issue affecting a production system?*  nop

#### Context

* *node version*: 
v12.18.3
* *module version with issue*: 
@hapi/joi-date: 2.0.1,
* *last module version without issue*: 
??
* *environment* (e.g. node, browser, native): 
node
* *used with* (e.g. hapi application, another framework, standalone, ...):
express
* *any other relevant information*:
typescript

#### What are you trying to achieve or the steps to reproduce?

```js
import JoiDate from '@hapi/joi-date';
```

#### What was the result you got?

<img width="872" alt="Captura de Tela 2021-02-23 às 20 41 01" src="https://user-images.githubusercontent.com/11557379/108923673-00d23180-7618-11eb-8139-466714c1a25a.png">

Could not find a declaration file for module '@hapi/joi-date'. '.../node_modules/@hapi/joi-date/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/hapi__joi-date` if it exists or add a new declaration (.d.ts) file containing `declare module '@hapi/joi-date';`

#### What result did you expect?

No errors

**Comment by jweyrich** [comment]
Use [joi](https://www.npmjs.com/package/joi) and [@joi/date](https://www.npmjs.com/package/@joi/date) instead.

**Comment by fnoquiq** [comment]
i can't do this using @joi/date

`Joi.date().format('YYYY-MM-DD').required()`
