### ISSUE TITLE
Doc fixes

### ISSUE THREAD

**Issue by daweimau** [sideway/joi-date#40]
**1 - npm package**

This [page](https://joi.dev/module/joi-date/api/) has the following block:

```md
Installation:
npm: npm install @hapi/joi-date

yarn: yarn add @hapi/joi-date
```

I think the actual package is now `@joi/date`, and that is stated correctly [here](https://joi.dev/module/joi-date/#install).

**2 - version**

They say 2.0.1, but we're on 2.1.0.

I would PR these changes but I can't seem to find the source document in this repo.

**Comment by yellowjacketcoder** [comment]
@daweimau I guess they've changed it on their own or somebody else's PR was merged. It's changed to the correct name now

**Comment by devinivy** [comment]
Yep, looks like it was handled here and this one can be closed out: https://github.com/sideway/joi.dev/pull/25
